### ISSUE TITLE
Add ability to enable/disable grading categories on a per course-basis.

### ISSUE THREAD

**Issue by PederHA** [PederHA/inginious-coding-style#5]
One course might not require the same grading categories as another, and as such it can be relevant to add some way to control which grading categories are enabled for each course. In order to minimize the amount of configration needed to achieve this, as well as not breaking existing configuration files, each course should be able to define their own overrides.

## Example Configuration

```yaml
enabled:
    - comments
    - modularity
    - structure
    - idiomaticity
categories:
  - id: custom_category
    name: Custom Category
    description: This is a custom category for the course PROG1001.
# Course override
overrides:
  prog1001:
     enabled:
        - comments
        - modularity
        - custom_category
```

In this example, a new category named `custom_category` is defined, but it is not activated globally. Furthermore, the course `PROG1001` enables its own set of active grading categories in the `overrides` section, and uses the `custom_category` grading category defined previously.

### The `PluginConfig.enabled` attribute

The way the code is written now, we refer to `PluginConfig.enabled` when we want to fetch the active grading categories. If this new functionality is to be added, we need to always have access to a `Course` object or a `courseid` (that MUST match the one found in the config) whenever we want to fetch enabled categories.

We could add a new method to `CodingStyleGrades` to fetch the enabled categories for the relevant course:

```py
class PluginConfig:
    def get_categories(self, course: Course) -> Dict[str, GradingCategory]:
        """Returns a list of enabled grading category IDs for a course."""
        if overrides := overrides.get(course.get_id()) and overrides.enabled:
            return return {k: v for k, v in self.enabled if k in overrides}
        return self.enabled
```

And thus every instance of `PluginConfig.enabled` should be replaced with `PluginConfig.get_categories(course)

### `PluginConfigIn.categories` & `PluginConfig.enabled`

In the current implementation of the plugin, `PluginConfigIn.categories` and `PluginConfigIn.enabled` are combined to a single attribute `PluginConfig.enabled`. Furthermore, we don't add categories that are defined but not enabled to the `PluginConfig.enabled` attribute. This needs to be completely rewritten in order to support the proposed changes, as we need to be able to separate the IDs of enabled categories and the category definitions themselves.
